version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./metadata:/app/metadata
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Uncomment the following section if you want to use Weaviate as your vector database
  # weaviate:
  #   image: semitechnologies/weaviate:1.19.6
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     QUERY_DEFAULTS_LIMIT: 25
  #     AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
  #     PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
  #     DEFAULT_VECTORIZER_MODULE: 'none'
  #     ENABLE_MODULES: ''
  #     CLUSTER_HOSTNAME: 'node1'
  #   volumes:
  #     - weaviate_data:/var/lib/weaviate
  #   restart: unless-stopped

# Uncomment if using Weaviate
# volumes:
#   weaviate_data: